### ISSUE TITLE
Doesn't apply to multiple folders

### ISSUE THREAD

**Issue by raphaelgoetter** [FrankFang/gulp-html-extend#11]
Hello,

My files are in several folders, like this : 

```
src/
  index.html
  folder1/
    index.html
  folder2/
    index.html 
```

But the plugin doesn't seem to manage several folders. With the following task, my root `index.html` file will always be overwritten by the other folder/index pages : 

```
gulp.task('extend', function () {
    gulp.src(['./src/*.html','./src/folder1/*.html'])
        .pipe(extender({annotations:true,verbose:false})) // default options
        .pipe(gulp.dest(destination))
})
```

Is it possible to manage multiple folders, and how ?

Thank you.

**Comment by FrankFang** [comment]
try this:
```
gulp.src('./src/{,folder1/}*.html')
```

**Comment by raphaelgoetter** [comment]
It works, thank you !
