### ISSUE TITLE
gulp-preprocess doesn't work when it's used in @@master file

### ISSUE THREAD

**Issue by fedotxxl** [FrankFang/gulp-html-extend#13]
Suppose I've got page `index.html` which uses `<!-- @@master  = /layout/_app.html -->`
I've got following build script:

    return gulp
        .src("./**.*html"))
        .pipe($.preprocess({context: preprocess}))
        .pipe($.htmlExtend({annotations: false, verbose: true, root: "./"}))
        .pipe(gulp.dest("./target))

When I use any annotation from `gulp-preprocess` in `index.html` it works as expected. When I use it in `_app.html` it doesn't work - looks like `htmlExtend` reads this file from disk

Is it possible to use pipe file if it's presented in pipe (may be this is not correct - I'm not node.js guy)?

**Comment by FrankFang** [comment]
I believe it's possible, let me see what I can do.

**Comment by FrankFang** [comment]
@fedotxxl  Have you tried to put htmlExtend before preprocess?

**Comment by fedotxxl** [comment]
Finally figured it out:

1. htmlExtend before preprocess -> works as expected
2. preprocess before htmlExtend:
2.1. `root` option of htmlExtend == gulp.dest -> works as expected
2.2. `root` option != gulp.dest -> preprocess doesn't work

**Comment by FrankFang** [comment]
Great. maybe I will look into 2.2 later. Thanks for feedback.

**Comment by fedotxxl** [comment]
I had to split build process:

preprocess builds files into tmp directory
htmlExtend reads files from tmp directory

It's annoying. Can you work on this problem?

**Comment by FrankFang** [comment]
@fedotxxl  Sorry, I'll try, but no promise :(    
For now I have no idea how to get /layout/_app.html for the output of preprocess.

**Comment by FrankFang** [comment]
How about to add a transform option
