### ISSUE TITLE
与gulp-changed组合使用疑问

### ISSUE THREAD

**Issue by flowerguo** [FrankFang/gulp-html-extend#23]
Hi，Frank。
在近期我在配置gulp遇到了疑问，我使用"gulp-changed"实现只编译修改过的文件。代码如下：

> gulp.task('extend', function(){
>     gulp.src(config.view.src)
>         .pipe(changed('src', {extension: '.html'})) 
>         .pipe(extender({annotations: true,verbose: true}))
>         .pipe(gulp.dest('src'))
>         .pipe(browserSync.stream());
> });

当我修改master页面时无法完成“extend”这个任务，修改子页面可以完成“extend”任务，这是为什么呢？

**Comment by FrankFang** [comment]
如果 master 变了，gulp-html-extend 会看 master 依赖了哪些文件，不会去看哪些文件依赖了 master，所以建议你还是每次都全部重新 extend。应该不会太慢。

**Comment by FrankFang** [comment]
如果太慢，再看有没有必要优化

**Comment by flowerguo** [comment]
事实上，好像是因为全部extend的影响，有时“browser-sync”不能自动刷新，需要手动刷新才能正确显示修改内容。如果一个项目的很多页面，比如有3、40个页面，每次重新extend好像比较费时吧。这是一点小疑问。谢谢 Frank 的解答~

**Comment by FrankFang** [comment]
browser-sync 应该可以把间隔时间调大一点
