### ISSUE TITLE
Extra lines appearing in generated pages if html has CRLF line-endings

### ISSUE THREAD

**Issue by MikhailPikalov** [FrankFang/gulp-html-extend#5]
My layout.html starts with following html
```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
```

and result looks like this:

```html
<!DOCTYPE html>

<html>

    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
```

My guess by quick look that this can be fixed by changing all entries of this regular expression **/\n|\r|\r\n/** to this regular expression **/\r\n|\r|\n/**.

**Comment by FrankFang** [comment]
Yeah, you got it.

**Comment by FrankFang** [comment]
Hi, @MikhailPikalov 
I did some test and pushed the version 0.5.6.  Could you run your gulp tasks again and tell me whether it works well?
Thx.

**Comment by MikhailPikalov** [comment]
Works just fine, no extra lines, thank you :)
