### ISSUE TITLE
Can't specify absolute path to master file

### ISSUE THREAD

**Issue by fedotxxl** [FrankFang/gulp-html-extend#6]
`<!-- @@master  = /master.html-->` looks for `master.html` relative to processed file. I think it should use root folder as starting point.

**Comment by FrankFang** [comment]
Absolute is not supported for now.      
I thought relative path is enough. But I'll push some code to make absolute path work next week, maybe.

**Comment by fedotxxl** [comment]
thank you

**Comment by fedotxxl** [comment]
Could you also implement it for `@@include` ?

**Comment by FrankFang** [comment]
Good idea. I will.

**Comment by FrankFang** [comment]
@fedotxxl  Hi, check out v1.1.0 see what happens. My test cases pass but I want to make sure it works for you. 

Usage:

add `root: /path_relative_to_cwd/` and run the task.

Good luck.

**Comment by fedotxxl** [comment]
Hi. Thank you, it works! But I've got one small problem with `root` param. I thought it's relative to `gulpfile.js`. But it's not true - it's relative to `/node_modules/gulp-html-extend` folder. So I have to use something like `root: "../../src/"`. Could you make it relative to gulpfile? I think this is expected behaviour

**Comment by FrankFang** [comment]
Thanks for your feedback. I am a fresh for Node, but I'll figure out what's the problem.

**Comment by FrankFang** [comment]
@fedotxxl   How about v1.1.2. I believe it works now.

**Comment by fedotxxl** [comment]
yep, it works!)
