### ISSUE TITLE
isRelativeToRoot bug in Windows

### ISSUE THREAD

**Issue by evanlask** [FrankFang/gulp-html-extend#7]
<pre>
function isRelativeToRoot(p){
    return p.indexOf(path.normalize(path.sep)) === 0
}
</pre>

On Windows path.sep = "\"
On OSX path.sep = "/"

root will not work on Windows but it will on OSX when including html like shown below.
@@include = /template/nav.html 

It may be safe to change that function to get it working on both platforms.
<pre>
function isRelativeToRoot(p){
    return p.indexOf('/') === 0
}
</pre>

**Comment by FrankFang** [comment]
Yeah. you are right.

**Comment by FrankFang** [comment]
Hi, try gulp-html-extend@1.1.3  :)
