### ISSUE TITLE
jsonString breaks with minus sign inside

### ISSUE THREAD

**Issue by Uncaught-Exception** [FrankFang/gulp-html-extend#8]
The jsonString-regex does not match json objects with a minus sign inside:

E.g. for the master regex the `[^-]` does not seem to be necessary, but breaks my code:
```var regex = /<!--\s*@@master\s*[= ]\s*(\S+)\s*(?:([^-]+)\s*)?-->/```

I cannot provide a variable containing a minus to my master template:
```<!-- @@master master.html {"foo":"bar-bar"} -->```

Even worse, this does not match at all and the `@@master` is not parsed at all.

**Comment by FrankFang** [comment]
I realize it is not very easy to match the json string. 
Maybe I will change the variable syntax.

`<!--@@master master.html @@foo bar-bar -->` something like this. :(

**Comment by Uncaught-Exception** [comment]
Thanks a lot! :)
